import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, Share2, Link, FileText, Copy, Check, Loader2, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog';
import { AnalysisResult } from '@/hooks/useWebsiteAnalyzer';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { generateAnalysisPDF } from '@/lib/pdfReport';
import { toast } from 'sonner';


interface ExportAnalysisProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult | null;
}

export function ExportAnalysis({ isOpen, onClose, result }: ExportAnalysisProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [shareLink, setShareLink] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const { user } = useAuth();

  const generateShareLink = async () => {
    if (!result || !user) {
      toast.error('Please sign in to share analyses');
      return;
    }

    setIsGenerating(true);
    try {
      const { data, error } = await supabase
        .from('saved_analyses')
        .insert([{
          user_id: user.id,
          url: result.url,
          score: result.score,
          analysis_data: JSON.parse(JSON.stringify(result)),
          is_public: true,
        }])
        .select('share_id')
        .single();

      if (error) throw error;

      const link = `${window.location.origin}/share/${data.share_id}`;
      setShareLink(link);
      toast.success('Share link generated!');
    } catch (error: any) {
      toast.error(error.message || 'Failed to generate share link');
    } finally {
      setIsGenerating(false);
    }
  };

  const copyLink = async () => {
    if (!shareLink) return;
    await navigator.clipboard.writeText(shareLink);
    setCopied(true);
    toast.success('Link copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadAsPDF = () => {
    if (!result) return;
    try {
      generateAnalysisPDF(result);
      toast.success('PDF report downloaded!');
    } catch (e: any) {
      toast.error(e?.message || 'Failed to generate PDF');
    }
  };

  const downloadAsText = () => {

    if (!result) return;

    // Create a simple text-based report
    const report = `
WebVision Analysis Report
========================

Website: ${result.url}
Quality Score: ${result.score}/100

IMAGES
------
Total: ${result.images.length} images found

FONTS
-----
Detected: ${result.fonts.detected.join(', ') || 'None detected'}
Google Fonts: ${result.fonts.googleFonts.join(', ') || 'None detected'}

COLORS
------
Palette: ${result.colors.slice(0, 10).join(', ') || 'None extracted'}

ICONS
-----
SVG Count: ${result.icons.svgCount}
Libraries: ${result.icons.libraries.join(', ') || 'None detected'}

ANIMATIONS
----------
CSS Animations: ${result.animations.cssAnimations.length}
Transitions: ${result.animations.transitions.length}
Keyframes: ${result.animations.keyframes.length}

META INFORMATION
----------------
HTTPS: ${result.meta.isHttps ? 'Yes' : 'No'}
Viewport: ${result.meta.hasViewport ? 'Yes' : 'No'}
Preload: ${result.meta.hasPreload ? 'Yes' : 'No'}
Responsive Images: ${result.meta.hasResponsiveImages ? 'Yes' : 'No'}

---
Generated by WebVision - ${new Date().toLocaleDateString()}
    `.trim();

    // Create and download file
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `webvision-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast.success('Report downloaded!');
  };

  const downloadAsJSON = () => {
    if (!result) return;

    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `webvision-analysis-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast.success('JSON exported!');
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md bg-gradient-to-br from-card via-card to-muted/30 border-border/50">
        <DialogTitle className="sr-only">Export Analysis</DialogTitle>
        
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center gap-3 mb-8">
            <motion.div 
              className="p-3 bg-gradient-to-br from-primary/20 to-accent/20 rounded-xl"
              whileHover={{ rotate: 10 }}
            >
              <Share2 className="w-6 h-6 text-primary" />
            </motion.div>
            <div>
              <h2 className="text-xl font-display font-bold">Export Analysis</h2>
              <p className="text-muted-foreground text-sm">Download or share your results</p>
            </div>
          </div>

          <div className="space-y-4">
            {/* Download Options */}
            <div className="space-y-3">
              <p className="text-sm font-medium text-muted-foreground">Download</p>

              <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                <Button
                  onClick={downloadAsPDF}
                  className="w-full h-12 justify-start rounded-xl bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70"
                >
                  <FileDown className="w-5 h-5 mr-3" />
                  <span className="flex-1 text-left">Download PDF Report</span>
                  <Download className="w-4 h-4 opacity-80" />
                </Button>
              </motion.div>

              <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                <Button
                  onClick={downloadAsText}
                  variant="outline"
                  className="w-full h-12 justify-start rounded-xl border-border/50 hover:bg-muted/50"
                >
                  <FileText className="w-5 h-5 mr-3 text-primary" />
                  <span className="flex-1 text-left">Download Report (TXT)</span>
                  <Download className="w-4 h-4 text-muted-foreground" />
                </Button>
              </motion.div>


              <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                <Button
                  onClick={downloadAsJSON}
                  variant="outline"
                  className="w-full h-12 justify-start rounded-xl border-border/50 hover:bg-muted/50"
                >
                  <FileText className="w-5 h-5 mr-3 text-accent-foreground" />
                  <span className="flex-1 text-left">Export as JSON</span>
                  <Download className="w-4 h-4 text-muted-foreground" />
                </Button>
              </motion.div>
            </div>

            {/* Share Options */}
            <div className="space-y-3 pt-4 border-t border-border/50">
              <p className="text-sm font-medium text-muted-foreground">Share</p>
              
              {!shareLink ? (
                <motion.div whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.99 }}>
                  <Button
                    onClick={generateShareLink}
                    disabled={isGenerating || !user}
                    className="w-full h-12 bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70 rounded-xl"
                  >
                    {isGenerating ? (
                      <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    ) : (
                      <Link className="w-5 h-5 mr-2" />
                    )}
                    {user ? 'Generate Share Link' : 'Sign in to share'}
                  </Button>
                </motion.div>
              ) : (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex gap-2"
                >
                  <input
                    type="text"
                    value={shareLink}
                    readOnly
                    className="flex-1 h-12 px-4 bg-muted/50 border border-border/50 rounded-xl text-sm truncate"
                  />
                  <Button
                    onClick={copyLink}
                    variant="outline"
                    className="h-12 px-4 rounded-xl"
                  >
                    {copied ? (
                      <Check className="w-5 h-5 text-green-500" />
                    ) : (
                      <Copy className="w-5 h-5" />
                    )}
                  </Button>
                </motion.div>
              )}
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
